### ISSUE TITLE
对当前Python脚本和算法做的一系列改善

### ISSUE THREAD

**Issue by Yang-Xijie** [JingyuNankin/Picture-to-line-draft#2]
作者你好 我在 <https://github.com/Yang-Xijie/Picture-to-line-draft> fork了这份项目并做出了一系列的修改

- 明确了转换函数的输入与输出类型为uint8的numpy矩阵 避免了数值控制
- 明确了kernel的意义 更改为kernel_size
- 最大值函数改为np.max 应该能提高运算速度
- 简化了算法判断逻辑 只使用一个max_color
- 添加了Python脚本cli参数控制
- 添加了线稿提取后的去脏处理
- 添加了一些注释 重构了代码 添加了assert保证合法输入

但由于我只关注Python脚本 对项目做出了比较大的修改 就没有提PR

作者觉得这些修改不错的话可以手动合并 [extract.py](https://github.com/Yang-Xijie/Picture-to-line-draft/blob/main/extract.py)

**Comment by JingyuNankin** [comment]
我看一下我自己代码，这个是一个很简单的图像处理，不过是我一年前弄的了。这里的&nbsp;kernel 变量并不是&nbsp;kernel_size ，你的理解有一点偏差。


我在我的代码里的第 53 行定义&nbsp;kernel = np.zeros((5,5))，定义卷积核（kernel）是一个 5 * 5 的数值全为 0 的矩阵。但是实际上卷积核不一定是数值全为 0 的方形矩阵，还可以是其它数据的矩阵。我这个代码写得不好，也有一定的误导性，因为我实际上没有卷积，就是算了一下那 5 * 5 区域的最大值，所以这个 5 * 5 的矩阵的数值显得没用。


输入图像





按照我之前写的，5 * 5 矩阵，取最大值：




以中间为 -8，周围一圈为 1，最外围一圈为 0 的矩阵为例。我的代码里的注释“#卷积”至“#反色”之间改为：
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ave_color = 0 # 再叫做 max_color 不合适，改为此名
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; for m in range(kernel_height):
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; for n in range(kernel_width):
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ave_color += raw_matrix[j + m][i + n] / 25


卷积核
kernel = np.matrix([[0, 0, 0, 0, 0], [0, 1, 1, 1, 0], [0, 1, -8, 1, 0],
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [0, 1, 1, 1, 0], [0, 0, 0, 0, 0]])





我在网上随便找了一篇关于图像处理与卷积核的博客：https://www.cnblogs.com/Liu-xiang/p/10259861.html，你可以简要阅读一下，希望你能对 kernel 有更深的理解。


总之感谢你的完善，如果你对图像处理感兴趣的话，祝你有更多研究成果！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JingyuNankin/Picture-to-line-draft"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 晚上6:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[JingyuNankin/Picture-to-line-draft] 对当前Python脚本和算法做的一系列改善 (Issue #2)





 
作者你好 我在 https://github.com/Yang-Xijie/Picture-to-line-draft fork了这份项目并做出了一系列的修改
  
明确了转换函数的输入与输出类型为uint8的numpy矩阵 避免了数值控制
 
明确了kernel的意义 更改为kernel_size
 
最大值函数改为np.max 应该能提高运算速度
 
简化了算法判断逻辑 只使用一个max_color
 
添加了Python脚本cli参数控制
 
添加了线稿提取后的去脏处理
 
添加了一些注释 重构了代码 添加了assert保证合法输入
  
但由于我只关注Python脚本 对项目做出了比较大的修改 就没有提PR
 
作者觉得这些修改不错的话可以手动合并 extract.py

**Comment by JingyuNankin** [comment]
你好，我再多说几句：
上一封电子邮件有插图，如果你是用Github网页版来看的话，可能看不到插图，希望你能够用电子邮箱来看。
我现在主要是在做服务器后端，还有QQ机器人这些，已经不怎么研究图像处理了，但是我这边还认识人在做图像处理。他是北航电子学院的。
不知道你有没有兴趣和我们进一步交流。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月7日(周四) 晚上6:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [JingyuNankin/Picture-to-line-draft] 对当前Python脚本和算法做的一系列改善 (Issue #2)




 
作者你好 我在 https://github.com/Yang-Xijie/Picture-to-line-draft fork了这份项目并做出了一系列的修改
  
明确了转换函数的输入与输出类型为uint8的numpy矩阵 避免了数值控制 

明确了kernel的意义 更改为kernel_size 

最大值函数改为np.max 应该能提高运算速度 

简化了算法判断逻辑 只使用一个max_color 

添加了Python脚本cli参数控制 

添加了线稿提取后的去脏处理 

添加了一些注释 重构了代码 添加了assert保证合法输入 
 
但由于我只关注Python脚本 对项目做出了比较大的修改 就没有提PR
 
作者觉得这些修改不错的话可以手动合并 extract.py

**Comment by Yang-Xijie** [comment]
感谢回复！网页版和邮箱都看不到图 但感觉意思已经传达到了
确实我没理解到用卷积核计算 之后也可以进一步改进算法ww
我的话看图像处理主要是个人兴趣吧 刚好搜到了这个仓库就想着用实际代码试一试 相关的研究可能不太有意向 😃

**Comment by JingyuNankin** [comment]
打个广告，我们这有一个小 QQ 群 904280379，我刚刚提的那个人也是我们社团的人，我们很欢迎您加入。可以进一步探讨图像处理，可以合作完成一些内容。我们后来从 Github“搬家”到 GitEE 去了，所以Github上东西并不多。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月7日(周四) 晚上10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JingyuNankin/Picture-to-line-draft] 对当前Python脚本和算法做的一系列改善 (Issue #2)




 
感谢回复！网页版和邮箱都看不到图 但感觉意思已经传达到了
 确实我没理解到用卷积核计算 之后也可以进一步改进算法ww
 我的话看图像处理主要是个人兴趣吧 刚好搜到了这个仓库就想着用实际代码试一试 相关的研究可能不太有意向 😃
